name: Bug report
description: Report a bug with Revanced++ patches
labels: ["Bug report"]
body:
  - type: markdown
    attributes:
      value: |
        # Revanced++ bug report
        Before submitting, search for [existing reports](../../issues?q=label%3A%22Bug+report%22).

  - type: input
    id: app
    attributes:
      label: App and version
      placeholder: e.g. YouTube 20.14.43
    validations:
      required: true

  - type: input
    id: patch
    attributes:
      label: Patch name
      placeholder: e.g. Hide ads
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
