blank_issues_enabled: false
contact_links:
  - name: 🗨 Discussions
    url: https://github.com/revanced/revanced-suggestions/discussions
    about: Have something in mind for Revanced++? Search for or start a new discussion!