name: Feature request
description: Suggest a new patch or improvement for Revanced++
labels: ["Feature request"]
body:
  - type: markdown
    attributes:
      value: |
        # Revanced++ feature request
        Before submitting, search for [existing requests](../../issues?q=label%3A%22Feature+request%22).

  - type: input
    id: app
    attributes:
      label: Target app
      placeholder: e.g. YouTube, Spotify
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature description
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Why is this useful?
    validations:
      required: true
